version: "3.8"
services:
  zookeeper-1:
    container_name: zookeeper-1
    image: zulfikar4568/zookeeper:2.8.0
    build:
      context: ./zookeeper
    volumes:
    - ./zookeeper/config/zookeeper-1/zookeeper.properties:/kafka/config/zookeeper.properties
    - ./zookeeper/data/zookeeper-1/:/tmp/zookeeper/
    networks:
    - kafka
  kafka-1:
    container_name: kafka-1
    image: zulfikar4568/kafka:2.8.0
    build: 
      context: ./kafka
    volumes:
    - ./kafka/config/kafka-1/server.properties:/kafka/config/server.properties
    - ./kafka/data/kafka-1/:/tmp/kafka-logs/
    networks:
    - kafka
  kafka-2:
    container_name: kafka-2
    image: zulfikar4568/kafka:2.8.0
    build: 
      context: ./kafka
    volumes:
    - ./kafka/config/kafka-2/server.properties:/kafka/config/server.properties
    - ./kafka/data/kafka-2/:/tmp/kafka-logs/
    networks:
    - kafka
  kafka-3:
    container_name: kafka-3
    image: zulfikar4568/kafka:2.8.0
    build: 
      context: ./kafka
    volumes:
    - ./kafka/config/kafka-3/server.properties:/kafka/config/server.properties
    - ./kafka/data/kafka-3/:/tmp/kafka-logs/
    networks:
    - kafka
  kafka-producer:
    container_name: kafka-producer
    image: zulfikar4568/kafka:2.8.0
    build: 
      context: ./kafka
    working_dir: /kafka
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    networks:
    - kafka
  kafka-consumer:
    container_name: kafka-consumer
    image: zulfikar4568/kafka:2.8.0
    build: 
      context: .
    working_dir: /kafka
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    networks:
    - kafka
networks: 
  kafka:
    name: kafka